source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem "jekyll-seo-tag"
gem "jekyll-theme-minimal"
gem "jekyll-relative-links"
gem "kramdown-parser-gfm"
gem "webrick"
gem "csv"
gem "base64"
gem "bigdecimal"